server:
  port: 8081

spring:
  mail:
    host: localhost
    port: 1025
    username:
    password:
    properties:
      mail:
        smtp:
          auth: false
    default-encoding: UTF-8

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/helo

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 6000

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.boot.autoconfigure: INFO
    org.springframework.boot.autoconfigure.jms.activemq: WARN


keycloak:
  server-url: http://localhost:8180
  realm: helo

  # Admin client for backend service-to-service operations
  admin-client-id: admin-cli
  admin-client-secret: 47Juv2fwxzFGtR5UCTKKK8LT9S3jkiV4

  # Public client for user login, refresh tokens, and profile access
  client-id: helo-app

helo:
  otp:
    expiry-seconds: 300

  mail:
    from: no-reply@helo.my
    subject-prefix: "[helo.my Identity]"

  profile:
    enrich-from-keycloak: true

  cache:
    user-profile-ttl: 600
