server:
  port: 8080  # Spring Boot now runs on standard port

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/helo_identity
    username: helo
    password: helo123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  mail:
    host: localhost
    port: 1025
    username:
    password:
    properties:
      mail:
        smtp:
          auth: false
    default-encoding: UTF-8

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/helo  # Keycloak now runs on 8081

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 6000

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.boot.autoconfigure: INFO
    org.springframework.boot.autoconfigure.jms.activemq: WARN

keycloak:
  server-url: http://localhost:8081
  realm: helo

  admin-client-id: admin-cli
  admin-client-secret: 47Juv2fwxzFGtR5UCTKKK8LT9S3jkiV4

  client-id: helo-app

helo:
  otp:
    expiry-seconds: 300

  mail:
    from: no-reply@helo.my
    subject-prefix: "[helo.my Identity]"

  profile:
    enrich-from-keycloak: true

  cache:
    user-profile-ttl: 600
