spring:
  mail:
    host: localhost
    port: 1025
    username:
    password:
    properties:
      mail:
        smtp:
          auth: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/helo

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 6000

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG

keycloak:
  server-url: http://localhost:8180
  realm: helo
  client-id: admin-cli
  client-secret: 47Juv2fwxzFGtR5UCTKKK8LT9S3jkiV4



